function SectionHowToPlay() {
    return (
        <section id="how-to-play" data-w-id="188a1cbe-f5f2-a28c-fb5f-7b23cda3aa9a" className="section-how-to-play wf-section">
            <div className="w-container">
                <h1>How to Play?</h1>
                <div className="w-layout-grid grid-9">
                    <img src="../../favicon-32x32.png" alt="pas trouvé"></img>
                    <p id="w-node-ffcd4019-46fa-420f-0b95-dc6053b685fc-3d3dc5f0"><strong>InterPool</strong> is a <strong>Sport Prediction Game with no loser</strong>, where the <strong>winners share the interests generated by the deposits of all participants.</strong></p>
                    <div id="w-node-_835689c6-c887-dba0-88d7-f2f2dcca6638-3d3dc5f0">⚠️</div>
                    <p>We are live on Goerli (Ethereum Testnet) and Mumbai (Polygon Testnet). Professional third parties will audit the InterPool code prior full deployment on the mainnet.</p>
                    <div>⚽</div>
                    <p><strong>First, press "Connect"</strong> on the top right of the page.<br />A step by step user guide is available <a href="https://irruption-lab.gitbook.io/interpool/welcome/getting-started" target="_blank" rel="noreferrer">here</a>.</p>
                    <div>⚽</div>
                    <p id="w-node-c8e0b4d8-5171-59f3-cc3c-fdbd40fb313e-3d3dc5f0"><strong>To join the prediction game you are required to get at least 1 ticket during the submission period.</strong><br />
                        In order to get tickets, you need to deposit a multiple of the unitary price (50 USDC). You can get free USDC directly on the InterPool app.</p>
                    <div id="w-node-_5d72efa9-d130-2e91-a5db-d85fac5728be-3d3dc5f0">⚽</div>
                    <p id="w-node-_6f064332-d5b5-a535-9ec3-99c9f7d41caf-3d3dc5f0"><strong>Once you got your ticket(s) you become eligible to enter the prediction game.</strong><br />This is the key moment where you need to show your prediction skills!<br />You don't necessarily need to be 100% correct, you just need to be better than the others to get higher rewards!
                    </p><div id="w-node-_20dbb91a-a1bb-22b9-5a25-a427b6707be8-3d3dc5f0">⚽</div><p id="w-node-dcd78d48-0867-a502-6033-7e5938725a3b-3d3dc5f0"><strong>At the end of the contest, prizes are shared based on the final rankings of all the participants. </strong><br />Details of the prize pool distribution is explained <a href="https://irruption-lab.gitbook.io/interpool/welcome/frequently-asked-questions#prizes-and-winning" target="_blank" rel="noreferrer">here</a>.
                    </p><div id="w-node-_1048304c-49a0-06cd-a9c4-555c570ffb31-3d3dc5f0">⚽</div><p id="w-node-_3f7c3c92-ee7e-12ec-0d5e-7c65038eeda3-3d3dc5f0"><strong>As long as you hold a ticket, you can join all the coming contests.</strong><br />You can also get your deposit back right after the end of each contest you participated in.</p>
                </div>
            </div>
        </section >
    )
}
export default SectionHowToPlay;